# Example configuration for Starship
add_newline = true

[directory]
truncation_length = 3

[git_branch]
symbol = "ğŸŒ¿ "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[nodejs]
format = "via [â¬¢ $version](bold green) "

[character]
success_symbol = "[âœ”ï¸](bold green)"
error_symbol = "[âœ–ï¸](bold red)"
